language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danielstoyanovv/fib -f ./server/Dockerfile.dev ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#  - docker build -t stoyanov1234/fib-server  ./server
  - docker build -t stoyanov1234/fib-server -f ./server/Dockerfile ./server
  - cd client
  - docker build -t stoyanov1234/fib-client -f Dockerfile .
script:
   - docker push stoyanov1234/fib-server
   - docker push stoyanov1234/fib-client
after_success:
   - docker run danielstoyanovv/fib npm test
