language: generic
sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in ./ruby/service-account.json.enc -out ./ruby/service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

  - docker build -t danielstoyanovv/fib -f ./server/Dockerfile.dev ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker build -t stoyanov1234/fib-server -f ./server/Dockerfile.dev  ./server
  - docker build -t stoyanov1234/fib-client ./client
script:
   - docker push stoyanov1234/fib-server
   - docker push stoyanov1234/fib-client
after_success:
   - docker run danielstoyanovv/fib npm test
