language: generic
sudo: required
services:
  - docker
before_install:
  - travis_wait 30 openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in ./ruby/service-account.json.enc -out ./ruby/service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - travis_wait 30 source $HOME/google-cloud-sdk/path.bash.inc
  - travis_wait 30 gcloud components update kubectl
  - travis_wait 30 gcloud auth activate-service-account --key-file service-account.json
  - travis_wait 30 gcloud config set project multi-k8s-451610
#  - travis_wait 30 gcloud config set compute/zone europe-central2-c
#  - travis_wait 30 gcloud container clusters get-credentials multi-cluster
#
#  - travis_wait 30 docker build -t danielstoyanovv/fib -f ./server/Dockerfile.dev ./server
#  - travis_wait 30 echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#
#  - travis_wait 30 docker build -t stoyanov1234/fib-server -f ./server/Dockerfile.dev  ./server
#  - travis_wait 30 docker build -t stoyanov1234/fib-client ./client
script:
#   - travis_wait 30 docker push stoyanov1234/fib-server
#   - travis_wait 30 docker push stoyanov1234/fib-client
after_success:
#   - travis_wait 30 docker run danielstoyanovv/fib npm test
