language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danielstoyanovv/fib -f ./server/Dockerfile.dev ./server
  - docker build -t danielstoyanovv/fib-nginx ./nginx
  - docker build -t danielstoyanovv/fib-client ./client
  - docker build -t danielstoyanovv/fib-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push danielstoyanovv/fib-nginx
  - docker push danielstoyanovv/fib-client
  - docker push danielstoyanovv/fib-server

script:
  - docker run danielstoyanovv/fib npm test
#
#after_success:
#  - docker build -t danielstoyanovv/fib-nginx ./nginx
#  - docker build -t danielstoyanovv/fib-client ./client
#  - docker build -t danielstoyanovv/fib-server ./server
#
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#
#  - docker push danielstoyanovv/fib-nginx
#  - docker push danielstoyanovv/fib-client
#  - docker push danielstoyanovv/fib-server


