name: fibonacci-sequence-app

services:
  postgres:
    image: "postgres:alpine"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 6546tre
    networks:
      - fibonacci-sequence-app
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 4000:4000
    networks:
      - fibonacci-sequence-app
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - fibonacci-sequence-app
    ports:
      - 3000:3000
    depends_on:
      - api
  redis-server:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - fibonacci-sequence-app
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
    networks:
      - fibonacci-sequence-app
    depends_on:
      - api
      - client

networks:
  fibonacci-sequence-app:
    driver: bridge